apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-world-frontend
  namespace: hello-world
  labels:
    app.kubernetes.io/name: hello-world-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-frontend
